services:
  db_mlaku_mulu:
    image: mariadb:10-focal
    container_name: db_mlaku_mulu
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - 3306:3306
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="${MYSQL_PASSWORD}" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db_mlaku_mulu:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 3306

volumes:
  db_mlaku_mulu: